### ISSUE TITLE
This didn't work for me.

### ISSUE THREAD

**Issue by danielecook** [drio/bio.brew#1]
I had to manually add this:

export PERL5LIB=/usr/local/Cellar/vcftools/0.1.11/lib/perl5/site_perl/

in my .bash_profile to get it to work. I see that you noted it - why isn't homebrew capable of handling this?

**Comment by drio** [comment]
Hi Daniel, 

Thanks for sending this.

The recipe takes care of [that](https://github.com/drio/bio.brew/blob/master/recipes/vcftools.sh#L19). Are you resourcing your session for the changes to take effect?
